[project]
name = "env"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi[all]",
    "pip",
    "pydantic-settings>=2.9.1",
    "scalar-fastapi",
    "sqlmodel>=0.0.24",
]
